language: c

compiler:
    - clang
    - gcc-4.8
    - gcc-4.9
    - gcc-5

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - gcc-4.9
            - gcc-5

env:
    - C_FLAGS=
    - C_FLAGS=-fsanitize=address

script:
    - mkdir build && cd build
    - cmake -DCMAKE_C_FLAGS=${C_FLAGS} ..
    - make VERBOSE=1
    - ctest -V
