language: c

compiler:
    - clang
    - gcc

env:
    - C_FLAGS=
    - C_FLAGS=-fsanitize=address

script:
    - mkdir build && cd build
    - cmake -DCMAKE_C_FLAGS=${C_FLAGS} ..
    - make VERBOSE=1
    - ctest -V
